### ISSUE TITLE
[Bug] Play.URL is a required field

### ISSUE THREAD

**Issue by KrisLange** [BTBurke/twiml#16]
I'm trying to use this library to generate the following XML.
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Play digits="9w9w9"></Play>
</Response>
```
I generate this XML using the following snippet
``` go
res := twiml.NewResponse()
res.Add(&twiml.Play{Digits: "9w9w9"})

b, _ := res.Encode()
```

The twiml library [requires `URL` to be set](https://github.com/BTBurke/twiml/blob/aacafc44cbe42ec4fa543cc25715782fa4d1d8c2/vocabulary.go#L335); however, Twilio does not require the `URL` field be set for `Play`.

I have confirmed by sending the following in response to a Twilio request, and it succeeded.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Play></Play>
</Response>
```

I believe the `URL` field should be removed from `Play`'s validation to support the above XML generation. Creating this issue to provide context for an incoming PR.

**Comment by BTBurke** [comment]
Thanks!
