### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by catvec** [BTBurke/twiml#5]
I am use Dep to manage my Go packages. By default it uses for the most recent Git tag as the version it pulls down.  

I was receiving an error related to `Dial` validation when using the `Sip` noun. It took me a second to realize that a fix for `Dial` validation in this circumstance was added ~10 days ago. And Dep was not pulling down the latest commit on master but instead the `v1.0.0` tag.  To fix this I made Dep track the `master` branch of this repository.

It would be helpful if a new tag was created with the `Dial` validation fix. 

If you are planning on not using tags in the future but instead having people track the `master` branch this is fine, feel free to close this issue. 

PS: Thank you so much for maintaining this library. It has made using Twilio with Go super easy!

**Comment by BTBurke** [comment]
Thanks for the heads up, I didn't even notice that was what was happening.  I'll push a new tag and at the same time I'm planning to switch it over to go modules format.  I've started using go.mod for everything.

**Comment by catvec** [comment]
Thanks. I didn't realize go.mod had hit stable.

**Comment by BTBurke** [comment]
Finally fixed this.  Only a year late, sorry!
