### ISSUE TITLE
[Bug] Dial.Number is a required field

### ISSUE THREAD

**Issue by andrewpage** [BTBurke/twiml#6]
I'm trying to generate the following TwiML:

```xml
<Response>
    <Dial>
        <Queue>my-queue-name</Queue>
    </Dial>
</Response>
```

Here is the Go code I am using:

```go
// Connect rep to personal queue
res := twiml.NewResponse()
dial := twiml.Dial{}
dial.Add(&twiml.Queue{
  Name: "my-queue-name",
})
res.Add(&dial)

// handle error on XML generate
body, err := res.Encode()
if err != nil {
    panic(err)
}
```

`Encode()` returns an error which, when paniced, outputs the following:
```
panic <nil> Invalid TwiML markup:
Invalid TwiML markup:
Dial did not pass validation <nil>
```

I've identified the bug in the code. `Dial.Number` field is explicitly required by validations (https://github.com/BTBurke/twiml/blob/master/vocabulary.go#L110), but it seems like you have carved out a case for the SIP verb block. The SIP verb is not the only `<Dial>` child that does not require a number. To my knowledge, `<Client>`, `<Conference>`, and `<Queue>` do not require a number.

I think an appropriate fix would be to make the `hasSIPChild` flag more general, to include all `<Dial>` children that don't require a number. I plan to implement this fix myself, but I wanted to document this bug in case I don't get around to it.

**Comment by flyandi** [comment]
Fixed this issue by accident with my last PR
